[package]
name = "benchmarks"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
rush = { path = "../crates/core" }
criterion.workspace = true

[[bench]]
name = "core_benchmarks"
harness = false
